### ISSUE TITLE
Resume parsing with a different grammar?

### ISSUE THREAD

**Issue by liamoc** [nineml/coffeegrinder#116]
Hi there,

Thanks for a very nice package for these kinds of general CFG parsers. I'm already using it very productively in my project.

In my project, I use parsers to parse just a prefix of the input. Based on this prefix, I may have to change the grammar I'm using, so I want to construct a new Parser and continue parsing from that point onwards using my new Parser. However, I can't seem to find a nice way to do this that doesn't incur a quadratic penalty from repeatedly copying the rest of the input into a new Token array over and over again.

What would be the best way to accomplish this? The way I see it, either a new method to change the grammar of an existing EarleyParser (and therefore regenerate all the other stuff that's in that class and set up in the constructor) would work, and then I could just resume parsing with the new grammar, or alternatively some means of telling a new EarleyParser to start at some offset rather than at the beginning of the token list.

Can you advise me?

Thanks again for the package and all of your help.

**Comment by ndw** [comment]
The functionality was already present, just not exposed. In 3.0.0f, which I hope to publish today, I've added 

```java
    /** After a successful prefix parse, this method continues parsing with a new parser.
     *
     * @return The (next) parse result.
     */
    GearleyResult continueParsing(GearleyParser parser);
```

To the `GearleyResult` class. That will allow you to continue parsing with a different parser. It will throw an exception if the parsers are incompatible. Only lightly tested.
